name: Push tests

on:
#  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.13.1
            plone: 6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          mkdir -p buildout-cache/{eggs,downloads}
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          buildout -c gha.cfg annotate
          buildout -c gha.cfg
      - name: test
        run: |
          bin/test -t !robot
